config/routes.rb
Rails.application.routes.draw do
  root to: 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :show, :create, :destroy]
  resources :pictures do
    collection do
      post :confirm
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user

  validates :content_or_image, presence: true
  validates :content, length: { maximum: 140 }

  mount_uploader :image, ImageUploader

  private

  def content_or_image
    content.presence or image.presence
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures

  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 255},
                              format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}

  before_validation{email.downcase!}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def show
  end

  def edit
  end

  def confirm
    @picture = Picture.new(picture_params)
    render :new if @picture.invalid?
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if @picture.save
      redirect_to pictures_path, notice: "投稿しました"
    else
      render "confirm"
    end
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "編集しました"
    else
      redirect_to edit_picture_path
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice: "削除しました"
  end

  private

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
      params.require(:picture).permit(:content, :image, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
      flash[:notice] = 'ログインしました'
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    else action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||=User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Images</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      <header>
        <div class="user">
          <% if logged_in? %>
            <%= link_to current_user.name, user_path(current_user.id) %>
            <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "アカウント作成", new_user_path %>
            <%= link_to "ログイン", new_session_path %>
          <% end %>
        </div>
        <div class="operation">
          <i class="fab fa-facebook-square fa-2x"></i>
          <%= link_to '一覧', pictures_path %>
          <% if logged_in? %>
            <%= link_to '投稿する', new_picture_path %>
          <% end %>
        </div>
      </header>
      <div class="row">
    <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url: choose_new_or_edit) do |form| %>
<% if picture.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

    <ul>
    <% picture.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="image">
    <%= form.label :image %>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/_left.html.erb
<div class="left col-md-2">
  <ul>
    <li><i class="fas fa-newspaper"></i>ニュース</li>
    <li><i class="fab fa-facebook-messenger"></i>Messenger</li>
    <li><i class="fas fa-tv"></i>Watch</li>
    <li>発見</li>
    <li><i class="fab fa-facebook-square"></i>ようこそ</li>
    <li><i class="fas fa-flag"></i>ページ</li>
  </ul>
</div>

app/views/pictures/_right.html.erb
<div class="right col-md-4">
  <p>知り合いかも</p>
</div>

app/views/pictures/confirm.html.erb
<%= render 'left' %>

<div class="main col-md-6">
  <h1>確認画面</h1>

  <%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
    <%= form.hidden_field :content %>
    <p><%= @picture.content %></p>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit "投稿する" %>
  <% end %>

  <%= form_with(model: @picture, url:new_picture_path, local:true, method: "get") do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
  <% end %>
</div>

<%= render 'right' %>

app/views/pictures/edit.html.erb
<%= render 'left' %>

<div class="main col-md-6">
  <h1>編集する</h1>
  <%= render 'form', picture: @picture %>
</div>

<%= render 'right' %>

app/views/pictures/index.html.erb
<%= render 'left' %>

<div class="main col-md-6">
  <h1>一覧画面</h1>
<p id="notice"><%= notice %></p>
  <table>
    <thead>
      <tr>
      </tr>
    </thead>

    <tbody>
      <% @pictures.each do |picture| %>
        <tr class="contribution">
          <td><%=picture.user.name %></td>
        </tr>
        <tr class="contribution">
          <td><%= picture.content %></td>
        </tr>
        <tr class="contribution">
          <td><%= image_tag (picture.image.url) if picture.image && picture.image.url %></td>
        </tr>
        <tr class="contribution">
          <td>
            <%= link_to '詳細', picture %>
            <%= link_to '編集', edit_picture_path(picture) %>
            <%= link_to '削除', picture, method: :delete, data: { confirm: '本当に削除しますか?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= render 'right' %>

app/views/pictures/new.html.erb
<%= render 'left' %>

<div class="main col-md-6">
  <h1>投稿する</h1>
  <%= render 'form', picture: @picture %>
</div>

<%= render 'right' %>

app/views/pictures/show.html.erb
<%= render 'left' %>

<div class="main col-md-6">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>content:</strong>
    <%= @picture.content %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= image_tag (@picture.image.url) if @picture.image && @picture.image.url %>
  </p>

  <%= link_to 'Back', pictures_path %>
</div>

<%= render 'right' %>

app/views/users/new.html.erb
<%= form_with(model: @user, local: true) do |f| %>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="account">
  <p><%= f.label :name %></p>
  <p><%= f.text_field :name %></p>

  <p><%= f.label :email %></p>
  <p><%= f.email_field :email %></p>

  <p><%= f.label :password %></p>
  <p><%= f.password_field :password %></p>

  <p><%= f.label :password %></p>
  <p><%= f.password_field :password_confirmation %></p>

  <p><%= f.submit "アカウントを作成する" %></p>
</div>
<% end %>

app/views/users/show.html.erb
<div class="profile">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <h1><%= @user.name %></h1>
  <p>メールアドレス </p>
  <p><%= @user.email %></p>
</div>